import 'react-toastify/dist/ReactToastify.css';

import { ClerkProvider } from '@clerk/nextjs'
import Footer from './../components/footer'
import { Inter } from 'next/font/google'
import NavBar from './../components/navbar'
import { fetchCategories } from '@/util/createClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categor = await fetchCategories()
  return (
    <ClerkProvider>
    <html lang="en">
      <body className='max-w-6xl mx-auto px-10 overflow-x-hidden'>
        
        <NavBar categories={categor}/>
        {children}
        <Footer/>
        </body>
    </html>

    </ClerkProvider>
  )
}
