import Footer from './../components/footer'
import { Inter } from 'next/font/google'
import NavBar from './../components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-6xl mx-auto px-10 overflow-x-hidden'>
        
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
